### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by grekpg** [kunicmarko20/SonataImporterBundle#6]
I have problems with setup.
(Symfony 4.4, Sonata admin 3.55.0)

AutoConfigure ImportConfiguration
To be able to auto-configure your ImportConfiguration they will have to implement KunicMarko\SonataImporterBundle\SonataImportConfiguration and configure format and adminClass methods along with other methods.

I add to admin implements AdminWithImport
I add to controller trait and implement interface 

```
class MyCrudController extends BaseController implements ControllerWithImport
{
    use ImportActionTrait;
```

but i dont understand what now.  
"To be able to auto-configure your ImportConfiguration they will have to implement"

Where i should put "ImportConfiguration" ? 

i see import action in panel  when i click i have 

`Call to a member function getImporter() on null`
in
` $importer = $this->importerFactory->getImporter($type = $import->file->getClientOriginalExtension());`

I create My importerConfiguration for admin - how to connect it to admin ? 
I register as service but still have error (Call to a member function getImporter() on null)

I see that my AdminContrller dont have ImporterFactory 

Thanks for any info.

**Comment by grekpg** [comment]
I add to services: 

```
KunicMarko\Importer\ImporterFactory:
        public: true
```

to CrudController 

```
$this->importerFactory = $this->get(ImporterFactory::class);
$importer = $this->importerFactory->getImporter($type = $import->file->getClientOriginalExtension());
```


but now have 
```
Warning: array_key_exists() expects parameter 2 to be array, null given
if (!array_key_exists($format, $this->importers)) {
```

Importers is empty :)

**Comment by kunicmarko20** [comment]
> but i dont understand what now.
"To be able to auto-configure your ImportConfiguration they will have to implement"

In ["How to use" section](https://github.com/kunicmarko20/SonataImporterBundle#how-to-use) you can see:

> If you haven't already go and read Importer documentation. I will assume you are already familiar with ImportConfiguration and I will just explain what is different in this bundle.

so read the documentation of https://github.com/kunicmarko20/importer and that should give you an idea of what you need to do.

> to CrudController
$this->importerFactory = $this->get(ImporterFactory::class);
$importer = $this->importerFactory->getImporter($type = $import->file->getClientOriginalExtension());
but now have
Warning: array_key_exists() expects parameter 2 to be array, null given
if (!array_key_exists($format, $this->importers)) {
Importers is empty :)

the only way importers are empty is if you didn't register both bundles like:

```
KunicMarko\Importer\Bridge\Symfony\ImporterBundle::class => ['all' => true],
KunicMarko\SonataImporterBundle\SonataImporterBundle::class => ['all' => true],
```

Because importers are registered in https://github.com/kunicmarko20/importer/blob/master/src/Bridge/Symfony/Resources/config/services.xml

If you have any more questions feel free to ask.

**Comment by grekpg** [comment]
Importers is registered but i check - sonataControllers are not services in my symfony 4.4  and "sonata-project/admin-bundle": "3.55.0",
so findTaggedServiceIds('sonata.importer.controller') in your AutoConfigureCompilerPass return only one controller - KunicMarko\SonataImporterBundle\Controller\ImportCRUDController

**Comment by kunicmarko20** [comment]
if your `sonataControllers` aren't autoconfigured then you need to manually tag them with `sonata.importer.controller` tag.

I explained it [here](https://github.com/kunicmarko20/SonataImporterBundle/issues/5#issuecomment-678271981) few days ago.

**Comment by grekpg** [comment]
sonataControllers in default are not services so is not autoconfigured. 
create service from mySonataCrudController and add tag not enough - sonata get CrudController as class not service so get new plain class not autoconfigured service.

**Comment by kunicmarko20** [comment]
I am sorry, but it is hard to understand what you wanted to say here.

sonataControllers are like any other controller, and they are services since Symfony 3.3 which you can see [here](https://symfony.com/blog/new-in-symfony-3-3-psr-4-based-service-discovery), so something around your configuration is wrong.

**Comment by grekpg** [comment]
ok Symfony Controllers yes - but I use SonataController/MyController so its not autoconfigured. And use own bundles (many) and its not have autodiscover SonataControllers . But ok now it work. 
(but maybe you add to doc information - sonata controllers are not autodiscover when its not in /Controller)
